apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: rollout-smoke-test
spec:
  args:
    - name: service-url
  metrics:
    - name: smoke-test
      provider:
        web:
          url: "{{ .Values.smokeTest.url }}"
          method: GET
      successCondition: result.status == "healthy"
      failureCondition: result.status != "healthy"
