apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: {{ .Values.containerPort }}
      imagePullSecrets:
        - name: ghcr-secret
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: "30s" }
        - setWeight: 50
        - pause: { duration: "30s" }
        - setWeight: 100
      analysis:
        templates:
          - templateName: rollout-smoke-test
        args:
          - name: service-url
            value: "{{ .Values.smokeTestUrl }}"
