apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/mng-g/portfolio-ci-cd.git"
    path: deploy/helm
    targetRevision: main
    helm:
      valueFiles:
        - staging-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
