name: Bug Report
description: Report a reproducible bug or regression.
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - mng-g
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please provide the following details to help us address the issue promptly.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a brief summary of the bug.
      placeholder: Brief description of the bug
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in detail, including steps to reproduce, expected behavior, and actual behavior.
      placeholder: Detailed description of the bug
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Specify the environment where the bug occurred (e.g., operating system, browser, device).
      placeholder: e.g., Windows 10, Chrome 89
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Provide the application version where the bug was found.
      placeholder: e.g., v1.2.3
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the bug.
      placeholder: Additional context
    validations:
      required: false
