name: Feature Request
description: Suggest an enhancement or new feature.
title: "[Feature Request]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - mng-g
body:
  - type: markdown
    attributes:
      value: |
        We appreciate your suggestions for improving our project. Please provide the following details to help us understand your request.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a concise summary of the feature request.
      placeholder: Brief description of the feature
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the proposed feature in detail, including its purpose and how it would benefit the project.
      placeholder: Detailed description of the feature
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative solutions
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots related to the feature request.
      placeholder: Additional context
    validations:
      required: false
